// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/logger/accesslog"
)

func main() {
	h := server.Default()
	//添加 accesslog打印访问日志功能
	h.Use(accesslog.New(
		accesslog.WithFormat(
			"[${time}] ${status} - ${latency} ${method} ${path} ${queryParams}")))

	register(h)
	h.Spin()
}
